import java.util.*;
import java.util.Random;
public class numberguessgame {
    static int highscore=0;
    public static void main(String[]args){
        Scanner sc= new Scanner(System.in);
        System.out.printf("                                            NUMBER GUESSING GAME                                                 \n");
        System.out.println("-------------------------------------------------------------------------------------------------------------------");
        System.out.println("\ndescription : this is a number guessing game where you have to correctly guess the number generated by computer\n");
        System.out.println("  Rules : you will only have 10 attemps to guess otherwise you will lose\n ");
        int score=0,attempts=10,i,count;
          
        do{
        Random ran = new Random();
            int Randomno= ran.nextInt(100)+1;
        
        for( count=1;count<=10;count++)
            {
      //  System.out.println("computer generated a random number ");
             
            System.out.print("guess the number :");
          int guess = sc.nextInt();
                
        if(guess==Randomno)
        {
            System.out.println("congratulations ! you've guessed it right !");
                if(count>=1 && count<=3){
                    score=score+10;
                }
                else if(count>3 && count<=6){
                    score=score+5;}
                    else{
                        score=score+1;}
                break;
        } 
        else if(guess>Randomno)
        {
            System.out.println("too high!..try guessing smaller number");
    }
            else  if(guess<Randomno){
                System.out.println("too low! try guessing larger number  ");
        }
                else
                    System.out.println("invalid input");
            System.out.printf("you have %d attempts left\n\n",--attempts);
            }
            if(count==11){
                System.out.println("Game over");
            }
                
                
            
            if(score>highscore)
                highscore=score;
            System.out.println("your score :"+score);
        System.out.println(" highscore :"+highscore);
            
            score=0;
            attempts=10;
        System.out.println("do you want to play again..\n1) 1 for yes\n 2) 0 for no ");
            i= sc.nextInt();
    } while(i!=0);
        
        
        
    }
}

